### ISSUE TITLE
带有异常的方法，生成注释时，缺少空格

### ISSUE THREAD

**Issue by xzxiaoshan** [freedommedal/idea-javadoc2#12]
![image](https://github.com/freedommedal/idea-javadoc2/assets/16459864/363526b8-29e6-4d37-808d-17e4bb02162b)

**Comment by freedommedal** [comment]
会抽空修正

**Comment by xzxiaoshan** [comment]
你好，我修复了一些问题，并且新增了预置变量，提交了 PR。


单红宇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "freedommedal/idea-javadoc2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月25日(星期三) 晚上6:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [freedommedal/idea-javadoc2] 带有异常的方法，生成注释时，缺少空格 (Issue #12)





 
会抽空修正

**Comment by freedommedal** [comment]
感谢修正
